class OfficeData {
  static const List<Map<String, String>> offices = [
    {'code': 'LYABO', 'name': 'أبوسليم'},
    {'code': 'LAMAA', 'name': 'المايه'},
    {'code': 'LYABY', 'name': 'الأبيار'},
    {'code': 'LYAGL', 'name': 'العجيلات'},
    {'code': 'LYAKF', 'name': 'الكفرة'},
    {'code': 'LYAMI', 'name': 'العامرية'},
    {'code': 'LYAZY', 'name': 'العزيزية'},
    {'code': 'LYBENA', 'name': 'بنغازي'},
    {'code': 'LYBNG', 'name': 'قصر بن غشير'},
    {'code': 'LYBUN', 'name': 'جامعة بنغازي'},
    {'code': 'LYCPO', 'name': 'البريد المركزي'},
    {'code': 'LYDAO', 'name': 'ذات العماد'},
    {'code': 'LYDHR', 'name': 'الظهرة'},
    {'code': 'LYDRN', 'name': 'درنة'},
    {'code': 'LYEJA', 'name': 'إلنجيلة'},
    {'code': 'LYEJD', 'name': 'اجدابيا'},
    {'code': 'LYGHO', 'name': 'الهضبة الخضراء'},
    {'code': 'LYGHR', 'name': 'قصر خيار'},
    {'code': 'LYGOR', 'name': 'قرجي'},
    {'code': 'LYHAO', 'name': 'حي الأندلس'},
    {'code': 'LYHBA', 'name': 'الحرابة'},
    {'code': 'LYHUN', 'name': 'هون'},
    {'code': 'LYJDO', 'name': 'جادو'},
    {'code': 'LYJIL', 'name': 'الجميّل'},
    {'code': 'LYJPO', 'name': 'جنزور'},
    {'code': 'LYKFA', 'name': 'الكفرة'},
    {'code': 'LYLAQ', 'name': 'البيضاء'},
    {'code': 'LYLMQ', 'name': 'البريقة'},
    {'code': 'LYLTD', 'name': 'غدامس'},
    {'code': 'LYMRA', 'name': 'مصراتة'},
    {'code': 'LYMSL', 'name': 'المسلاتة'},
    {'code': 'LYMZA', 'name': 'مزدة'},
    {'code': 'LYNLT', 'name': 'نالوت'},
    {'code': 'LYQBL', 'name': 'بني وليد'},
    {'code': 'LYQEC', 'name': 'المرج'},
    {'code': 'LYQEJ', 'name': 'القرابولي'},
    {'code': 'LYQGH', 'name': 'غريان'},
    {'code': 'LYQKO', 'name': 'الخمس'},
    {'code': 'LYQZL', 'name': 'زليتن'},
    {'code': 'LYQZT', 'name': 'الزاوية'},
    {'code': 'LYRBN', 'name': 'الرقبان'},
    {'code': 'LYRHB', 'name': 'الرحيبات'},
    {'code': 'LYRIN', 'name': 'الرياينة'},
    {'code': 'LYRLN', 'name': 'رقدالين'},
    {'code': 'LYSBA', 'name': 'صبراتة'},
    {'code': 'LYSBI', 'name': 'سبها'},
    {'code': 'LYSEM', 'name': 'سوق الخميس'},
    {'code': 'LYSGA', 'name': 'سوق الجمعة'},
    {'code': 'LYSPO', 'name': 'صياد'},
    {'code': 'LYSRM', 'name': 'صرمان'},
    {'code': 'LYSRO', 'name': 'طريق السواني'},
    {'code': 'LYSRX', 'name': 'سرت'},
    {'code': 'LYSSO', 'name': 'بريد السويحلي'},
    {'code': 'LYSWO', 'name': 'السواني'},
    {'code': 'LYTEG', 'name': 'تيجي'},
    {'code': 'LYTJR', 'name': 'تاجوراء'},
    {'code': 'LYTOP', 'name': 'طبرق'},
    {'code': 'LYTRH', 'name': 'ترهونة'},
    {'code': 'LYUFP', 'name': 'جامعة طرابلس (أ)'},
    {'code': 'LYUSP', 'name': 'حي الواحات'},
    {'code': 'LYWAX', 'name': 'زوارة'},
    {'code': 'LYYFN', 'name': 'يفرن'},
    {'code': 'LYZHR', 'name': 'الزهراء'},
    {'code': 'LYZLN', 'name': 'زلطن'},
    {'code': 'LYZTN', 'name': 'الزنتان'},
    {'code': 'LYBOK', 'name': 'ابوكماش'},
    {'code': 'LYQPO', 'name': 'القبة'},
  ];

  static const List<Map<String, String>> nonDeliveryReasons = [
    {'code': '10', 'name': 'العنوان غير صحيح'},
    {'code': '12', 'name': 'المستلم غير متواجد'},
    {'code': '13', 'name': 'رفض الاستلام'},
    {'code': '17', 'name': 'العنوان خاطئ'},
    {'code': '18', 'name': 'البعيثة متضررة أو تالفة أو يوجد نواقص'},
    {'code': '21', 'name': 'في انتظار الدفع'},
    {'code': '24', 'name': 'ظرف قاهر أو غير متوقع'},
    {'code': '28', 'name': 'المستلم انتقل لعنوان جديد'},
    {'code': '59', 'name': 'أسباب أخرى'},
  ];

  static const List<Map<String, String>> nonDeliveryMeasures = [
    {'code': 'A', 'name': 'إعادة جدولة التسليم أو اتخاذ إجراء آخر اليوم'},
    {'code': 'B', 'name': 'إعادة جدولة التسليم أو اتخاذ إجراء آخر غدا'},
    {'code': 'C', 'name': 'تم إشعار المستلم'},
    {'code': 'D', 'name': 'تم إشعار المرسل في انتظار الرد'},
    {'code': 'E', 'name': 'تم إرجاع البريد إلى المرسل'},
    {'code': 'F', 'name': 'تم إعادة التوجيه'},
    {'code': 'G', 'name': 'إعادة فحص البعيثة'},
    {'code': 'H', 'name': 'تم حجزها'},
    {'code': 'I', 'name': 'تم إشعار المكتب المرسل'},
    {'code': 'J', 'name': 'المستلم سيقوم بالاستلام من المكتب'},
    {'code': 'K', 'name': 'عدم التسليم بناءً على طلب المرسل'},
    {'code': 'L', 'name': 'تأجيل التسليم بناءً على طلب المستلم'},
    {'code': 'M', 'name': 'يتم التأكد من عنوان المستلم'},
    {'code': 'N', 'name': 'إعادة تغليف البعيثة'},
    {'code': 'O', 'name': 'في انتظار الإجراء التالي'},
  ];
}
